name: QR code testing

on:
  push:
    branches:
      - 1.1.1_qr_code_print_json
  
jobs:
  build_qr_code_related_modules:

    runs-on: ubuntu-latest
    steps:
      - name: Clear artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 10mins

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v10
        with:
          mirrors: '[{ "id": "MavenCentral", "mirrorOf": "central", "url": "https://repo.maven.apache.org/maven2" },{ "id": "Artifactory", "mirrorOf": "artifactory", "url": "http://52.172.8.144:8040/artifactory" }]'
          repositories: '[{ "id": "MavenCentral", "url": "https://repo.maven.apache.org/maven2", "releases": { "enabled": "true" } },{ "id": "Release", "name": "libs-release", "url": "http://52.172.8.144:8040/artifactory/libs-release", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }, { "id": "Snapshots", "name": "libs-snapshot", "url": "http://52.172.8.144:8040/artifactory/libs-snapshot", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'

      - name: Setup branch name
        run: |
          echo "::set-env name=BRANCH_NAME::$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')"
          echo ${{ env.BRANCH_NAME }}

      - name: Setup settings.xml
        run: |
          mvn -v
          cp -f ~/.m2/settings.xml $GITHUB_WORKSPACE/settings.xml
          cat $GITHUB_WORKSPACE/settings.xml

      - name: Build modules
        run: mvn clean install -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml -f registration/pom.xml

      - name: Log into docker registry
        run: echo "${{ secrets.RELEASE_DOCKER_HUB }}" | docker login -u ${{ secrets.ACTOR_DOCKER_HUB }} --password-stdin

      - name: Build docker of printing stage
        run: docker build -t $IMAGE_NAME ./registration/registration-processor/post-processor/registration-processor-printing-stage/
        env:
          IMAGE_NAME: registration-processor-printing-stage

      - name: Push docker image
        run: |
          IMAGE_ID=$NAMESPACE/$IMAGE_NAME
          echo $IMAGE_ID
          echo $BRANCH_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:$BRANCH_NAME
          docker push $IMAGE_ID:$BRANCH_NAME
        env:
          NAMESPACE: wuriguinea
          IMAGE_NAME: registration-processor-printing-stage